<?php

	$rows = '';

	foreach ($params["objetos"] as $objeto) {

		$classes = array();

		$rows .= '<tr';

		// if (isset($objeto["status"]) && $objeto['status'] == 0) {
		// 	$classes[] = 'desativada';
		// }

		if (count($classes) > 0) {
			$rows .= ' class="' . implode(" ", $classes) . '"';
		}

		$rows .= '>';
		$rows .= '<th scope="row">';
		$rows .= '<small>' . $iniCount++ . '</small>';
		$rows .= '</th>';

		if (isset($table["acoesMassa"])) {
			$rows .= '<td>';
    	$rows .= '<input type="checkbox" name="objetos[]" value="' . $objeto["id"] . '" />';
    	$rows .= '</td>';
    }

		foreach ($table['fields'] as $key => $f) {

			$classes = array();

			$rows .= '<td';

			if (isset($f['align'])) {
				$classes[] = $f['align'];
			}

			if (isset($f['preview'])) {
				$classes[] = 'ver_conteudo';
			}

			if (count($classes) > 0) {
				$rows .= ' class="' . implode(" ", $classes) . '"';
			}

			$rows .= '>';

			if ($key == 'thumbnail') {
				$rows .= '<div class="myThumbnail">';
				if (existeArquivo(eval($f['dir']))) {
					$rows .= '<img width="40px" class="img-rounded" src="' . eval($f['path']) . '" />';
					$rows .= '<div>';
					$rows .= '<img src="' . eval($f['path']) . '" />';
					$rows .= '</div>';
				}
				else {
					$rows .= '<img width="40px" class="img-rounded" src="imagens/user.gif" />';
				}
				$rows .= '</div>';
			}
			else {

				$rows .= '<span';
				$rows .='>';

				if (isset($f['link'])) {
					$rows .= '<a href="' . eval($f['link']['link']);
					if (isset($order) && !empty($order)) {
						$rows .= '&order=' . $order;
					}
					$rows .=  '">';
				}

				if (isset($f['content'])) {
					$rows .= eval($f['content']);
				}
				else {
					$rows .= $objeto[$key];
				}

				if (isset($f['link'])) {
					$rows .= '</a>';
				}

				$rows .= '</span>';

			}

			$rows .= '</td>';

		}

		if (isset($table["acoes"]) && count($table["acoes"]) > 0) {
			foreach ($table["acoes"] as $nomeAcao => $acao) {
				$rows .= '<td align="center">';
				$rows .= '<a ';
				$rows .= 'href="?modulo=' . $modulo;
				$arr1 = $arr2 = array();
				foreach ($acao as $key => $value) {
					$arr1[] = $key . "=" . eval($value);
					$arr2[] = '\'' . $key . '\':' . '\'' . eval($value) . '\'';
				}
				if (isset($pagina) && !empty($pagina) && $pagina > 1) {
					$arr1[] = 'p=' . $pagina;
					$arr2[] = '\'p\':' . $pagina;
				}
				if (isset($order) && !empty($order)) {
					$arr1[] = 'order=' . $order;
					$arr2[] = '\'order\':\'' . $order . '\'';
				}
				if (isset($exibir) && !empty($exibir) && $exibir != QUANTIDADE_POR_PAGINA) {
					$arr1[] = 'exibir=' . $exibir;
					$arr2[] = '\'exibir\':' . $exibir . '';
				}
				$rows .= "&" . implode("&", $arr1);
				$rows .= '"';
				$rows .= ' onclick="excluir(\'' . $modulo . '\', {';
				$rows .= implode(",", $arr2);
				$rows .= '});return false;"';
				$rows .= '>';
				$rows .= $nomeAcao;
				$rows .= '</a>';
				$rows .= '</td>';
			}
		}

		$rows .= '</tr>';
	}
?>
