<?php
	$configuracoes = new Configuration(array(
			"type" => "ini"
		)
	);
	$configuracoes = $configuracoes->initialize()->parse('configuracoes');
	$params = $this->getParams();
?>
<!DOCTYPE HTML>
<html>
<head>
<meta charset="UTF-8" />
<title><?php echo $configuracoes->configuracao->sigla; echo " &rsaquo; Sistema de gerenciamento"; if (!empty($params["title"])) echo " &rsaquo; " . $params["title"]; ?></title>
<link rel="icon" href="favicon.ico" type="image/gif"> 
<?php 
	include (DIR_ROOT.'/views/includes/css.html');
	include (DIR_ROOT.'/views/includes/javascript.html');	  
?>
</head>
<body>
	
	<header role="logo">
		<div class="inner">
			<a href="index.php">
				<hgroup>
					<h1><?php echo $configuracoes->configuracao->sigla; ?></h1>
				</hgroup>
			</a>
		</div>
	</header>
	
	<div class="inner main" style="border-top: 3px solid #2e6a98;">
		
		<div id="primary" class="primary" role="main">
			
			<?php if (isset($_SESSION[PREFIX . "loginId"])) {  ?>
			
			<nav role="breadcrumbs">
				<ol class="breadcrumb">
					<li>
						<a href="index.php"><?php echo $configuracoes->configuracao->sigla; ?></a>
					</li>
					
					<?php
						
						if (isset($params["breadcrumbs"])) {
							
							// percorre os itens do breadcrumb para calcular o tamanho total dele
							// se o tamanho for maior do que o esperado será tirada a diferença do maior item
							
							$tamanhoBreadcrumb = 5; 
							foreach ($params["breadcrumbs"] as $key => $value) {
								foreach ($value as $titulo => $link) {
									$tamanhoBreadcrumb = $tamanhoBreadcrumb + (strlen($titulo) + 3);	
								}
							}
							
							$diferenca = 0;
							
							// 95 é a quantidade de caracteres que cabe na barra de breadcrumbs
							// 19 é a média de caracteres que cabem em cada item do breadcrumb para totalizar os 95
							
							// calcula a sobra
							if ($tamanhoBreadcrumb > 95) {
								$diferenca = $tamanhoBreadcrumb - 95;
							}
								
							foreach ($params["breadcrumbs"] as $key => $value) {
								foreach ($value as $titulo => $link) {
									echo '<li>';
									if (!empty($link)) {
										echo '<a href="' . $link . '">';
									}
									if ($tamanhoBreadcrumb > 95 && strlen($titulo) > 19) {
										echo substr($titulo, 0, strlen($titulo) - $diferenca) . ' ...';
									}
									else {
										echo $titulo;
									}
									if (!empty($link)) {
										echo '</a>';
									}
									echo '</li>';
								}
							}
						}
					?>
					
				</ol>
			</nav>
			
			<?php }  ?>
			
			<?php if (isset($_GET['modulo'])) echo getMensagem($_GET['modulo']); ?>
			
			<?php echo $contents; ?>
			
		</div>
	</div>
	<footer>
		<?php if (isset($_SESSION[PREFIX . "loginId"])) { ?>
		<p>Você acessou como <a href="?modulo=index&acao=alterar&id=<?php echo $_SESSION[PREFIX . "loginId"]; ?>"><?php echo $_SESSION[PREFIX . "loginNome"]; ?></a> (<a href="sair.php">Sair</a>)</p>
		<?php } ?>
		<?php echo $configuracoes->configuracao->sigla . " - " . $configuracoes->configuracao->nome . " © " . date('Y'); ?>
	</footer>
</body>
</html>