<?php
	$params = $this->getParams();
	$usuario = $params["usuario"];
?>

<style>
	[class*='col-'] {
		margin-bottom: 10px;
	}
</style>

<form method="post">
	<input type="hidden" name="Usuario[id]" value="<?php echo $usuario["id"]; ?>" />
	<div class="grid">
		<div class="col-2-12">
			<div class="content">
				<label class="control-label" for="Nome">Nome:</label>
			</div>
		</div>
		
		<div class="col-10-12">
			<div class="content">
				<input class="form-control" type="text" name="Usuario[nome]" value="<?php echo $usuario["nome"]; ?>" autofocus="autofocus" />
			</div>
		</div>
	</div>
	
	<div class="grid">
		<div class="col-2-12">
			<div class="content">
				<label class="control-label" for="Login">Login:</label>
			</div>
		</div>
		
		<div class="col-4-12">
			<div class="content">
				<input class="form-control" type="text" name="Usuario[login]" value="<?php echo $usuario["login"]; ?>" />
			</div>
		</div>
		
		<div class="col-2-12">
			<div class="content">
				<label class="control-label" for="Senha">Senha:</label>
			</div>
		</div>
		
		<div class="col-4-12">
			<div class="content">
				<input class="form-control" type="password" name="Usuario[senha]" />
			</div>
		</div>
	</div>
		
	<div class="grid">
		<div class="col-2-12">
			<div class="content">
				<label class="control-label" for="Permissão">Permissão:</label>
			</div>
		</div>
		<div class="col-4-12">
			<div class="content">
				<select class="form-control" name="Usuario[permissao]">
					<option value="">--Selecione--</option>
					<?php
						foreach ($params["permissoes"] as $permissao) {
							echo '<option';
							if($usuario["permissao"] == $permissao["id"]) {
								echo ' selected="selected"';
							}
							echo ' value="'.$permissao["id"].'">';
							echo $permissao["nome"];
							echo '</option>';
						}
					?>
				</select>
			</div>
		</div>
	</div>
	
	<input class="btn btn-default" type="submit" value="Salvar" />
</form>

