<form method="post">
	<div class="grid">
		<div class="col-3-12">
			<div class="content">
				&nbsp;
			</div>
		</div>
		<div class="col-4-12">
			<div class="content">	
		      <h2>Login</h2>
		      <input type="text" class="form-control" name="login" placeholder="Login" required="" autofocus="" requiredmessage="Login deve ser informado" />
		      <input type="password" class="form-control" name="senha" placeholder="Senha" required="" requiredmessage="Senha deve ser informada"/>
		      <br />
		      <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>   
			</div>
		</div>
		<div class="col-4-12">
			<div class="content">
				&nbsp;
			</div>
		</div>
	</div>
</form>