<?php
	$params = $this->getParams();
	$compromissos = $params["compromissos"];
	$fisioterapeutas = $params["fisioterapeutas"];
	$fisioterapeuta = $params["fisioterapeuta"];
	$pacientes = $params["pacientes"];
	$dia = 1;
	$mes = $params["mes"];
	$ano = $params["ano"];
	$holidays = $params["holidays"];
?>

<script>

	function init () {
		var objetos1 = [<?php echo $pacientes; ?>];
		$(".autocomplete1").autocomplete({
		  source: objetos1
		}).bind('blur', function() {
			var nome = $(this).val();
			$.ajax({
				method: "POST",
				url: "views/agenda/ajax3.php?acao=dados",
				dataType: "json",
				data: {nome: nome}
			}).done(function(response) {
				$('#paciente').val(response.id);
				if (response.telefoneResidencial) {
					$('#telefoneResidencial').val(response.telefoneResidencial);
				}
				if (response.foto) {
					$('#foto').attr('src', response.pathFoto);
					$('#fotoPaciente').val(response.foto);
				}
				if (response.telefoneCelular) {
					$('#telefoneCelular').val(response.telefoneCelular);
				}
				$('#button').prop('disabled', false);
			});
		}).bind('focus', function(){
			$('#button').prop('disabled', true);
		});

		$("a[rel=modal]").click(function(ev){
			ev.preventDefault();
			// remove qualquer mensagem de validação/processamento
			$('#validation').remove();
			// id da janela modal
			var janela = "#janela1";
			// id do elemento
			var idCompromisso = parseInt($(this).attr("data-id"));
			// data e hora do compromisso
			var dataHora = $(this).attr("data-dh").split("T");
			var data = dataHora[0];
			var hora = dataHora[1];
			// calcula dinamicamente o tamanho da máscara baseado no tamanho atual do documento
			var maskHeight = $(document).height();
			var maskWidth = $(window).width();
			$('#mascara').css({'width':maskWidth,'height':maskHeight});
			// centralizando a janela modal na tela
			var left = ($(window).width()/2) - ($(janela).width()/2);
			var offset = $(document).scrollTop();
			var viewportHeight = $(window).height();
			var top = (offset  + (viewportHeight/2)) - ($(janela).outerHeight()/2);

			$('#mascara').fadeTo("slow", 0.8, function() {
				if (idCompromisso == 0) {
					var fisioterapeuta = $('#fisioterapeutas').val();
					$('#f' + fisioterapeuta).prop('checked', 'checked');
					$('#m0').prop('checked', 'checked');
				}
				else {
					$('#id').val(idCompromisso);
					// recuperar os dados do compromisso
					$.ajax({
						method: "POST",
						url: "views/agenda/ajax3.php?acao=recupera",
						dataType: "json",
						data: {id : idCompromisso}
					}).done(function(response) {
						$('#tipo').val(response.tipo);
						$('#paciente').val(response.paciente);
						$('#nomePaciente').val(response.nomePaciente);
						$('#telefoneResidencial').val(response.telefoneResidencial);
						$('#telefoneCelular').val(response.telefoneCelular);
						$('#lembrete').val(response.lembrete);
						$('#observacoes').val(response.observacoes);
						$('#m' + response.marcador).prop('checked', 'checked');
						$('#excluirGrid').css('display', 'block');
						if (response.pathFoto) {
							$('#foto').prop('src', response.pathFoto);
						}
						var fisioterapeutas = response.fisioterapeutas.split(',');
						for (f in fisioterapeutas) {
							$('#f' + fisioterapeutas[f]).prop('checked', 'checked');
						}
					});
				}

				$('#data').val(data);
				$('#hora').val(hora);
				$(janela).css({'top':top,'left':left});
				$(janela).show();

			});
		});

		$("#mascara").click(function(){
			$(this).hide();
			$(".window").hide();
			clear();
		});

		$('.fechar').click(function(ev){
			ev.preventDefault();
			$("#mascara").hide();
			$(".window").hide();
			$("#excluirGrid").css('display', 'none');
			clear();
		});

	}

	function clear() {
		$('#id').val(0);
		$('#paciente').val(0);
		$('#form input:text').each(function(){
			$(this).val('');
		});
		$('#form #foto').attr('src', 'imagens/user.gif');
		$('#form #fotoPaciente').val('');
		$('#form textarea').each(function(){
			$(this).val('');
		});
		$('#form select').each(function(){
			$(this).find("option:first").attr('selected','selected');
		});
		$('#form input:checkbox').each(function(){
			$(this).prop('checked', '');
		});
		$('#form input:radio').each(function(){
			$(this).prop('checked', '');
		});
	}

	$(document).ready(function(){
		init();
		$('#fisioterapeutas').trigger("change");
	});

</script>

<div class="grid top-items">
	<div class="col-1-1">
		<div class="content">
			<a href="?modulo=agenda&acao=cadastrar">
				<div class="item">
					<span class="ti-save"></span>
					<span class="icon-name">Novo compromisso</span>
				</div>
			</a>
		</div>
	</div>
</div>

<div class="grid">
	<div class="col-2-11">
		<div class="content">
			<div style="float: left; margin-right:7px;">
				<div href="#janela1" class="circle circle3" style="margin-left:0;"></div>
				<span>Livre</span>
			</div>
			<?php
				foreach (Agenda::getTipos() as $key => $value) {
					echo '<div style="float: left; margin-right:7px;">';
					echo '<div class="circle circle' . $key . '" style="margin-left:0;"></div>';
					echo '<span>' . $value . '</span>';
					echo '</div>';
				}
			?>
		</div>
	</div>
</div>

<div id="mascara"></div>

<div class="window" id="janela1">
    <a href="#" class="fechar">X Fechar</a>
    <div id="validation-container"></div>
    <form id="form" method="post">
    	<input type="hidden" id="id" name="id" value="0" />
			<input type="hidden" id="paciente" name="paciente" value="0" />
	    <div class="grid">
	    	<div class="col-3-12">
	    		<div class="content">
	    			<label for="Tipo de Compromisso">Tipo de Compromisso:</label>
	    		</div>
	    	</div>
	    	<div class="col-4-12">
	    		<div class="content">
	    			<select id="tipo" class="form-control" name="tipo">
	    				<?php
	    					foreach (Agenda::getTipos() as $key => $value) {
	    						echo '<option value="' . $key . '">' . $value . '</option>';
	    					}
	    				?>
	    			</select>
	    		</div>
	    	</div>
	    </div>
	    <div class="grid">
	    	<div class="col-3-12">
	    		<div class="content">
	    			<label for="Fisioterapeuta">Fisioterapeutas:</label>
	    		</div>
	    	</div>
	    	<div class="col-7-12">
	    		<div class="content">
	    			<?php
	    				foreach ($fisioterapeutas as $f) {
	    					echo '<label class="checkbox-inline">';
	    					echo '<input name="fisioterapeutas[]" id="f' . $f["id"] . '" type="checkbox" ';
								echo 'value="' . $f["nome"] . '-' . $f["id"] . '" />';
	    					echo $f["nome"];
	    					echo '</label>';
	    				}
	    			?>
	    		</div>
	    	</div>
	    </div>
	    <div class="grid">
	    	<div class="col-3-12">
	    		<div class="content">
	    			<label for="Data">Data:</label>
	    		</div>
	    	</div>
	    	<div class="col-3-12">
	    		<div class="content">
	    			<input id="data" class="form-control datepicker" id="data" placeholder="Data do compromisso"
							name="data" type="text" autocomplete="off" />
	    		</div>
	    	</div>
				<div class="col-2-12">
	    		<div class="content">
	    			<label for="Hora">Hora:</label>
	    		</div>
	    	</div>
	    	<div class="col-3-12">
	    		<div class="content">
	    			<input class="form-control hora" id="hora" name="hora" placeholder="Hora do compromisso"
							type="text" maxlength="5" autocomplete="off" />
	    		</div>
	    	</div>
	    </div>
			<div class="grid">
	    	<div class="col-3-12">
	    		<div class="content">
	    			<label for="Foto">Foto:</label>
	    		</div>
	    	</div>
	    	<div class="col-3-12">
	    		<div class="content">
	    			<img id="foto" class="img-thumbnail img-responsive" style="width: 60%;" src="imagens/user.gif" alt="" />
						<input id="fotoPaciente" type="hidden" name="fotoPaciente" value="" />
	    		</div>
	    	</div>
	    </div>
	    <div class="grid">
	    	<div class="col-3-12">
	    		<div class="content">
	    			<label for="Paciente">Paciente:</label>
	    		</div>
	    	</div>
	    	<div class="col-8-12">
	    		<div class="content">
	    			<input class="form-control autocomplete1" id="nomePaciente" name="nomePaciente"
							placeholder="Nome do paciente" size="60" type="text" />
	    		</div>
	    	</div>
	    </div>
	    <div class="grid">
	    	<div class="col-3-12">
	    		<div class="content">
	    			<label for="Telefone">Telefone Residencial:</label>
	    		</div>
	    	</div>
	    	<div class="col-3-12">
	    		<div class="content">
	    			<input class="form-control telefoneResidencial" id="telefoneResidencial"
							name="telefoneResidencial" placeholder="Telefone Residencial" size="40" type="text" autocomplete="off" />
	    		</div>
	    	</div>
				<div class="col-2-12">
	    		<div class="content">
	    			<label for="Telefone">Telefone Celular:</label>
	    		</div>
	    	</div>
	    	<div class="col-3-12">
	    		<div class="content">
	    			<input class="form-control telefoneCelular" id="telefoneCelular" name="telefoneCelular"
							placeholder="Telefone Celular" size="40" type="text" autocomplete="off" />
	    		</div>
	    	</div>
	    </div>
	    <div class="grid">

	    </div>
	    <div class="grid">
	    	<div class="col-3-12">
	    		<div class="content">
	    			<label for="Lembrete">Lembrete:</label>
	    		</div>
	    	</div>
	    	<div class="col-8-12">
	    		<div class="content">
	    			<textarea class="form-control" id="lembrete" placeholder="Lembrete" name="lembrete" cols="90"
							rows="2" maxlength="255"></textarea>
	    		</div>
	    	</div>
	    </div>
	    <div class="grid">
	    	<div class="col-3-12">
	    		<div class="content">
	    			<label for="Observações">Observações:</label>
	    		</div>
	    	</div>
	    	<div class="col-8-12">
	    		<div class="content">
	    			<textarea class="form-control" id="observacoes" placeholder="Observações" name="observacoes"
							cols="90" rows="2" maxlength="255"></textarea>
	    		</div>
	    	</div>
	    </div>
			<div class="grid">
	    	<div class="col-3-12">
	    		<div class="content">
	    			<label for="Fisioterapeuta">Marcadores:</label>
	    		</div>
	    	</div>
	    	<div class="col-7-12">
	    		<div class="content css3-radios">
						<?php
	    				foreach (Agenda::getMarcadores() as $key => $value) {
								list($class, $constante) = explode("-", $key);
	    					echo '<label class="radio-inline';
								$hint = Agenda::getHint($constante);
								if (!empty($hint)) {
									echo ' hint--top hint--info"';
									echo ' data-hint="' . $hint . '"';
								}
								echo '">';
	    					echo '<input id="m' . $constante . '" class="' . $class . '" name="marcador" type="radio" ';
								echo 'value="' . $constante . '" />';
	    					echo '<span>' . $value . '</span>';
	    					echo '</label>';
	    				}
	    			?>
	    		</div>
	    	</div>
	    </div>
	    <div class="grid" id="excluirGrid" style="display:none;">
	    	<div class="col-3-12">
	    		<div class="content">
	    			<label>&nbsp;</label>
	    		</div>
	    	</div>
	    	<div class="col-7-12">
	    		<div class="content">
	    			<a id="excluir" href="#">Excluir compromisso</a>
	    		</div>
	    	</div>
	    </div>
	    <input id="button" class="btn btn-default" type="button" value="Salvar" />
	</form>
</div>

<div class="fc-toolbar">
	<div class="fc-left">
		<div class="fc-button-group">
			<button id="<?php echo date('Y-m-d', strtotime('first day of previous month')); ?>" type="button" class="fc-prev-button fc-button fc-state-default fc-corner-left">
				<span class="fc-icon fc-icon-left-single-arrow"></span>
			</button>
			<button id="<?php echo date('Y-m-d', strtotime('first day of next month')); ?>"  type="button" class="fc-next-button fc-button fc-state-default fc-corner-right">
				<span class="fc-icon fc-icon-right-single-arrow"></span>
			</button>
		</div>
		<button id="<?php echo date('Y-m-d', strtotime('first day of this month')); ?>" type="button" class="fc-today-button fc-button fc-state-default fc-corner-left fc-corner-right">Hoje</button>
	</div>
	<div class="clear">&nbsp;</div>
</div>

<table width="100%" border="0" class="calendar agenda" id="f2">
	<thead>
		<th colspan="7">
			<?php
				if (count($fisioterapeutas) > 0) {
					echo '<select id="fisioterapeutas" name="fisioterapeuta">';
					foreach ($fisioterapeutas as $f) {
						echo '<option id="fisioterapeuta' . $f["id"] . '" value="' . $f["id"] . '"';
						echo '">' . $f["nome"] . '</option>';
					}
					echo '</select>';
				}
			?>
			<select id="mes" name="mes">
				<option id="mes1" value="1"<?php if($mes == 1) echo ' selected="selected"'; ?>>Janeiro</option>
				<option id="mes2" value="2"<?php if($mes == 2) echo ' selected="selected"'; ?>>Fevereiro</option>
				<option id="mes3" value="3"<?php if($mes == 3) echo ' selected="selected"'; ?>>Março</option>
				<option id="mes4" value="4"<?php if($mes == 4) echo ' selected="selected"'; ?>>Abril</option>
				<option id="mes5" value="5"<?php if($mes == 5) echo ' selected="selected"'; ?>>Maio</option>
				<option id="mes6" value="6"<?php if($mes == 6) echo ' selected="selected"'; ?>>Junho</option>
				<option id="mes7" value="7"<?php if($mes == 7) echo ' selected="selected"'; ?>>Julho</option>
				<option id="mes8" value="8"<?php if($mes == 8) echo ' selected="selected"'; ?>>Agosto</option>
				<option id="mes9" value="9"<?php if($mes == 9) echo ' selected="selected"'; ?>>Setembro</option>
				<option id="mes10" value="10"<?php if($mes == 10) echo ' selected="selected"'; ?>>Outubro</option>
				<option id="mes11" value="11"<?php if($mes == 11) echo ' selected="selected"'; ?>>Novembro</option>
				<option id="mes12" value="12"<?php if($mes == 12) echo ' selected="selected"'; ?>>Dezembro</option>
			</select>
			<select id="ano" name="ano">
				<?php
				for ($i=2013; $i<=$ano+2; $i++) {
					echo '<option id="ano' . $i . '" value="' . $i . '"';
					if ($i == $ano) {
						echo ' selected="selected"';
					}
					echo '">' . $i . '</option>';
				}
				?>
			</select>
			<img id="loader" src="imagens/ajax-loader-agenda.gif" style="display: none;" />
		</th>
	</thead>
	<tbody id="result-ajax">
		<?php include ('monta.php'); ?>
	</tbody>
</table>

<script>

	$("#button").click(function(){

		$('#validation').remove();

		var campos = [];

		if ($("#nomePaciente").val() == '') {
			alert($("#nomePaciente").val());
			campos.push('Paciente');
		}

		if ($("#form input:checkbox:checked").length == 0) {
			campos.push('Fisioterapeutas');
		}

		if (campos.length > 0) {
			$('<div/>', {
				id : 'validation',
		    class : 'alert alert-danger',
		    text : 'O(s) campo(s) ' + campos.join(', ') + ' é(são) obrigatório(s)'
			}).appendTo('#validation-container');
			return;
		}

		var dados = {};

		var inputs = $('#janela1 input:hidden');
		$(inputs).each(function(){
			dados[$(this).attr('name')] = $(this).val();
		});

		var inputs = $('#janela1 select');
		$(inputs).each(function(){
			dados[$(this).attr('name')] = $(this).val();
		});

		var inputs = $('#janela1 input:text');
		$(inputs).each(function(){
			dados[$(this).attr('name')] = $(this).val();
		});

		var inputs = $('#janela1 input:radio:checked');
		$(inputs).each(function(){
			dados[$(this).attr('name')] = $(this).val();
		});

		var inputs = $('#janela1 textarea');
		$(inputs).each(function(){
			dados[$(this).attr('name')] = $(this).val();
		});

		var fisioterapeutas = [];
		inputs = $('#janela1 input:checkbox:checked');

		$(inputs).each(function(){
			fisioterapeutas.push($(this).val());
		});

		dados['fisioterapeutas'] = fisioterapeutas.join(',');

		$.ajax({
			method: "POST",
			url: "views/agenda/ajax3.php?acao=cadastra",
			dataType: "json",
			data: {dados}
		}).done(function(response) {
			$('<div/>', {
				id : 'validation',
			    class : 'alert alert-' + response.type,
			    text : response.message
			}).appendTo('#validation-container');
			$('#mes').trigger("change");
		});
	});

	$("#excluir").click(function(ev){
		ev.preventDefault();
		if (confirm('Tem certeza que deseja excluir?')) {
			var id = $('#id').val();
			$.ajax({
				method: "POST",
				url: "views/agenda/ajax3.php?acao=exclui",
				data: {id : id}
			}).done(function(response) {
				$('#mes').trigger("change");
				$('.fechar').trigger("click");
			});
		}
	});

	$("#mes").on("change", function(){
		var mes = $("#mes").val();
		var ano = $("#ano").val();
		var fisioterapeuta = $("#fisioterapeutas").val();
		$("#loader").css("display", "inline");
		$.ajax({
			method: "POST",
			url: "views/agenda/ajax.php",
			dataType: "json",
			data: {mes: mes, ano: ano, fisioterapeuta: fisioterapeuta}
		}).done(function(response) {
			$(".fc-prev-button").attr('id', response.prevData);
			$(".fc-next-button").attr('id', response.nextData);
			$('#result-ajax tr:not(:first)').children().remove();
			$('#result-ajax tr:first-child').after(response.result);
			$("#loader").css("display", "none");
			init();
		});
	});

	$("#ano").on("change", function(){
		var mes = $("#mes").val();
		var ano = $("#ano").val();
		var fisioterapeuta = $("#fisioterapeutas").val();
		$("#loader").css("display", "inline");
		$.ajax({
			method: "POST",
			url: "views/agenda/ajax.php",
			dataType: "json",
			data: {mes: mes, ano: ano, fisioterapeuta: fisioterapeuta}
		}).done(function(response) {
			$(".fc-prev-button").attr('id', response.prevData);
			$(".fc-next-button").attr('id', response.nextData);
			$('#result-ajax tr:not(:first)').children().remove();
			$('#result-ajax tr:first-child').after(response.result);
			$("#loader").css("display", "none");
			init();
		});
	});

	$("#fisioterapeutas").on("change", function(){
		var mes = $("#mes").val();
		var ano = $("#ano").val();
		var fisioterapeuta = $("#fisioterapeutas").val();
		$("table.calendar").attr('id', 'f' + fisioterapeuta);
		$("#loader").css("display", "inline");
		$.ajax({
			method: "POST",
			url: "views/agenda/ajax.php",
			dataType: "json",
			data: {mes: mes, ano: ano, fisioterapeuta: fisioterapeuta}
		}).done(function(response) {
			$(".fc-prev-button").attr('id', response.prevData);
			$(".fc-next-button").attr('id', response.nextData);
			$('#result-ajax tr:not(:first)').children().remove();
			$('#result-ajax tr:first-child').after(response.result);
			$("#loader").css("display", "none");
			init();
		});

	});

	$(".fc-prev-button").on("click", function(){
		var data = $(".fc-prev-button").attr('id');
		var fisioterapeuta = $("#fisioterapeutas").val();
		$("#loader").css("display", "inline");
		$.ajax({
			method: "POST",
			url: "views/agenda/ajax.php",
			dataType: "json",
			data: {data: data, fisioterapeuta: fisioterapeuta}
		}).done(function(response) {
			$("#mes" + response.mes).prop("selected", true);
			if ($("#ano" + response.ano).length == 0) {
				$('<option/>', {
					id: '#ano' + response.ano,
					value: response.ano,
					selected: 'selected',
					text: response.ano
				}).appendTo('#ano');
			}
			$("#ano" + response.ano).prop("selected", true);
			$(".fc-prev-button").attr('id', response.prevData);
			$(".fc-next-button").attr('id', response.nextData);
			$('#result-ajax tr:not(:first)').children().remove();
			$('#result-ajax tr:first-child').after(response.result);
			$("#loader").css("display", "none");
			init();
		});
	});

	$(".fc-next-button").on("click", function(){
		var data = $(".fc-next-button").attr('id');
		var fisioterapeuta = $("#fisioterapeutas").val();
		$("#loader").css("display", "inline");
		$.ajax({
			method: "POST",
			url: "views/agenda/ajax.php",
			dataType: "json",
			data: {data: data, fisioterapeuta: fisioterapeuta}
		}).done(function(response) {
			$("#mes" + response.mes).prop("selected", true);
			if ($("#ano" + response.ano).length == 0) {
				$('<option/>', {
					id: '#ano' + response.ano,
					value: response.ano,
					selected: 'selected',
					text: response.ano
				}).appendTo('#ano');
			}
			$("#ano" + response.ano).prop("selected", true);
			$(".fc-prev-button").attr('id', response.prevData);
			$(".fc-next-button").attr('id', response.nextData);
			$('#result-ajax tr:not(:first)').children().remove();
			$('#result-ajax tr:first-child').after(response.result);
			$("#loader").css("display", "none");
			init();
		});
	});

	$(".fc-today-button").on("click", function(){
		var data = $(this).attr('id');
		var fisioterapeuta = $("#fisioterapeutas").val();
		$("#loader").css("display", "inline");
		$.ajax({
			method: "POST",
			url: "views/agenda/ajax.php",
			dataType: "json",
			data: {data: data, fisioterapeuta: fisioterapeuta}
		}).done(function(response) {
			$("#mes" + response.mes).prop("selected", true);
			$("#ano" + response.ano).prop("selected", true);
			$(".fc-prev-button").attr('id', response.prevData);
			$(".fc-next-button").attr('id', response.nextData);
			$('#result-ajax tr:not(:first)').children().remove();
			$('#result-ajax tr:first-child').after(response.result);
			$("#loader").css("display", "none");
			init();
			$("html, body").animate({
				scrollTop: $("#today").offset().top
			}, 1000);
		});

	});

</script>
