<?php
	$params = $this->getParams();
	$compromisso = $params["compromisso"];
	$pacientes = $params["pacientes"];
	$fisioterapeutas = $params["fisioterapeutas"];
?>

<style>
	[class*='col-'] {
		margin-bottom: 10px;
	}
</style>

<script>

	$(function() {
	    var objetos1 = [<?php echo $pacientes; ?>];
	    $(".autocomplete1").autocomplete({
	      source: objetos1
    	}).bind('blur', function() {
    		var nome = $(this).val();
    		$.ajax({
    			method: "POST",
    			url: "views/agenda/ajax3.php?acao=telefones",
    			dataType: "json",
    			data: {nome: nome}
    		}).done(function(response) {
    			$('#telefoneResidencial').val(response.telefoneResidencial);
    			$('#telefoneCelular').val(response.telefoneCelular);
    		});
    	});
  	})
 
</script>

<form method="post">

	<input name="id" type="hidden" value="<?php echo $compromisso["id"]; ?>" />
	
	<div class="grid">
		<div class="col-3-12">
			<div class="content">
				<label for="Fisioterapeuta">Tipo de Compromisso:</label>
			</div>
		</div>
		<div class="col-4-12">
			<div class="content">
				<select class="form-control" name="tipo">
					<?php
						$tipos = Agenda::getTipos();
						foreach ($tipos as $key => $value) {
							echo '<option';
							if ($compromisso["tipo"] == $key) {
								echo ' selected="selected"';
							}
							echo ' value="' . $key . '">' . $value . '</option>';
						}
					?>
				</select>
			</div>
		</div>
	</div>
	
	<div class="grid">
		<div class="col-3-12">
			<div class="content">
				<label for="Fisioterapeuta">Fisioterapeutas:</label>
			</div>
		</div>
		<div class="col-7-12">
			<div class="content">
				<?php
					foreach ($fisioterapeutas as $f) {
						echo '<label class="checkbox-inline">';
						echo '<input name="fisioterapeutas[]" id="f' . $f["id"] . '" ';
						if (in_array($f["nome"] . "-" . $f["id"], $compromisso["fisioterapeutas"])) {
							echo 'checked="checked" ';
						}
						echo 'type="checkbox" value="' . $f["nome"] . '-' . $f["id"] . '" />';
						echo $f["nome"];
						echo '</label>';
					}
				?>
			</div>
		</div>
	</div>
	
	<div class="grid">
		<div class="col-3-12">
			<div class="content">
				<label for="Paciente">Paciente:</label>
			</div>
		</div>
		<div class="col-7-12">
			<div class="content">
				<input class="form-control autocomplete1" id="paciente" placeholder="Nome do paciente" name="nomePaciente" size="60" type="text" value="<?php echo $compromisso["nomePaciente"]; ?>" autocomplete="off" />
			</div>
		</div>
	</div>
	
	<div class="grid">
		<div class="col-3-12">
			<div class="content">
				<label for="Data">Data:</label>
			</div>
		</div>
		<div class="col-3-12">
			<div class="content">
				<input id="data" class="form-control datepicker" placeholder="Data do compromisso" name="data" type="text" value="<?php echo $compromisso["data"]; ?>" autocomplete="off" />
			</div>
		</div>
	</div>
	
	<div class="grid">
		<div class="col-3-12">
			<div class="content">
				<label for="Hora">Hora:</label>
			</div>
		</div>
		<div class="col-3-12">
			<div class="content">
				<input class="form-control hora" id="hora" name="hora" placeholder="Hora do compromisso" type="text" maxlength="5" value="<?php echo $compromisso["hora"]; ?>" autocomplete="off" />
			</div>
		</div>
	</div>
	
	
	<div class="grid">
		<div class="col-3-12">
			<div class="content">
				<label for="Telefone">Telefone Residencial:</label>
			</div>
		</div>
		<div class="col-3-12">
			<div class="content">
				<input class="form-control telefoneResidencial" id="telefoneResidencial" placeholder="Telefone Residencial" name="telefoneResidencial" size="40" type="text" value="<?php echo $compromisso["telefoneResidencial"]; ?>" autocomplete="off" />
			</div>
		</div>
	</div>
	
	<div class="grid">
		<div class="col-3-12">
			<div class="content">
				<label for="Telefone">Telefone Celular:</label>
			</div>
		</div>
		<div class="col-3-12">
			<div class="content">
				<input class="form-control telefoneCelular" id="telefoneCelular" placeholder="Telefone Celular" name="telefoneCelular" size="40" type="text" value="<?php echo $compromisso["telefoneCelular"]; ?>" autocomplete="off" />
			</div>
		</div>
	</div>
	
	<div class="grid">
		<div class="col-3-12">
			<div class="content">
				<label for="Lembrete">Lembrete:</label>
			</div>
		</div>
		<div class="col-7-12">
			<div class="content">
				<textarea class="form-control" id="lembrete" placeholder="Lembrete" name="lembrete" cols="90" rows="2" maxlength="255"><?php echo $compromisso["lembrete"]; ?></textarea>
			</div>
		</div>
	</div>
	
	<div class="grid">
		<div class="col-3-12">
			<div class="content">
				<label for="Observações">Observações:</label>
			</div>
		</div>
		<div class="col-7-12">
			<div class="content">
				<textarea class="form-control" id="observacoes" placeholder="Observações" name="observacoes" cols="90" rows="2" maxlength="255"><?php echo $compromisso["observacoes"]; ?></textarea>
			</div>
		</div>
	</div>

	<input class="btn btn-default" type="submit" value="Salvar" /> 

</form>